spring:
  security.oauth2.client:
    registration:
      google:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}
      facebook:
        clientId: ${FACEBOOK_APP_ID}
        clientSecret: ${FACEBOOK_APP_SECRET}
        scope:
          - email
          - public_profile
      github:
        clientId: ${GITHUB_APP_ID}
        clientSecret: ${GITHUB_APP_SECRET}